"""
In Python, all exceptions must be instances of a class that derives from BaseException.
In a try statement with an except clause that mentions a particular class, that clause
also handles any exception classes derived from that class (but not exception classes
from which it is derived).

Two exception classes that are not related via subclassing are never equivalent,
even if they have the same name.

The built-in exceptions can be generated by the interpreter or built-in functions.
Except where mentioned, they have an "associated value" indicating the detailed cause
of the error. This may be a string or a tuple of several items of information
(e.g., an error code and a string explaining the code).

The associated value is usually passed as arguments to the exception class' constructor.

User code can raise built-in exceptions. This can be used to test an exception handler
or to report an error condition "just like" the situation in which the interpreter
raises the same exception; but beware that there is nothing to prevent user code
from raising an inappropriate error.

The built-in exception classes can be subclassed to define new exceptions; programmers
are encouraged to derive new exceptions from the Exception class or one of its
subclasses, and not from BaseException.

The class hierarchy for built-in exceptions is::

BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
      |    +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      |    +-- RecursionError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning
"""
